#!/usr/bin/python

# cat /proc/net/dev | grep --color=auto wlp60s0 | awk '{print $3":"$11":"}' | ./internet-speed.py

import sys
import pickle
import pathlib
import math


value = ['MB/s','KB/s', 'B/s']


def sanitize(sant):
    index = 0
    sant /= 1024**(len(value)-1)
    for speed in value:
        if sant < 1:
            sant *= 1024
            index += 1
    try:
        return f'{sant:.2f} {value[index]}'
    except IndexError:
        return f'{sant:.3f} {value[2]}'


for line in sys.stdin:
    curr_dwn, curr_up, _ = line.split(':')
    curr = {
        'd': int(curr_dwn),
        'u': int(curr_up)
    }

    with open('interdata.pkl', 'rb') as rd_pkl:
        old_speed = pickle.load(rd_pkl)
        dwn, upld = sanitize(
            float(curr['d']) - float(old_speed['d'])), sanitize(
            float(curr['u']) - float(old_speed['u']))
        # print(f'|Speed|n|Download| {dwn:20}\n|Upload|{upld:20}')
        print(f'⬇️ {dwn} ⬆️ {upld}')

    with open('interdata.pkl', 'wb') as wr_pkl:
        pickle.dump(curr, wr_pkl)
