#!/bin/sh
cat /proc/net/dev | grep --color=auto wlp60s0 | awk '{print $2":"$10":"}' | internet-speed

case $BLOCK_BUTTON in
    1) notify-send 'Left Click';;
    2) notify-send 'Middle Click';;
    3) notify-send 'Right Click';;
esac