#!/bin/sh
alias_fish="$HOME/.config/fish/alias.fish"

rmabbr $HOME/.config/fish/alias.fish # Cleaning up the abbrs

sed "s/\s*#.*$//;/^\s*$/d" "$HOME/.config/.fshalias" |
	awk '{print "abbr " $0}' |
	sed 's/[[:space:]]/ /g' > $alias_fish 2>/dev/null

rsfish	# Restarting Fish
