#!/bin/sh
echo " Finding and converting all ppt files to pdf " &&
	libreoffice --headless --invisible --convert-to pdf *.ppt 2>/dev/null &&
	echo " Removing .ppt files " &&
		rm *.ppt 2>/dev/null

echo " Finding and converting all pptx files to pdf " &&
	libreoffice --headless --invisible --convert-to pdf *.pptx 2>/dev/null
	echo " Removing .pptx files " &&
		rm *.pptx 2>/dev/null



