#!/bin/bash
# Output locations. Unactivated progs should go to /dev/null.
shell_shortcuts="$HOME/.shortcuts"
fish_shortcuts="$HOME/.config/fish/shortcuts.fish"

# Clean up
rmabbr $HOME/.config/fish/shortcuts.fish

# Remove, prepare files
printf "# vim: filetype=sh\\n" > "$fish_shortcuts"
printf "# vim: filetype=sh\\nalias " > "$shell_shortcuts"

# Format the `bmdirs` file in the correct syntax and sent it to all three configs.
sed "s/\s*#.*$//;/^\s*$/d" "$HOME/.config/bmdirs" | tee >(awk '{print $1"=\"cd "$2" && ls -a\" \\"}' >> "$shell_shortcuts") \
	>(awk '{print "abbr", $1, "\"cd " $2 "; and ls -a\""}' >> "$fish_shortcuts")

# Format the `configs` file in the correct syntax and sent it to both configs.
sed "s/\s*#.*$//;/^\s*$/d"  "$HOME/.config/bmfiles" | tee >(awk '{print $1"=\"nvim "$2"\" \\"}' >> "$shell_shortcuts") \
	>(awk '{print "abbr", $1, "\"nvim "$2"\""}' >> "$fish_shortcuts")

# Fish restart
rsfish
