abbr vga "vg activate"
abbr vgd "vg deactivate"
abbr vgi "vg init"
abbr syncpay "rsync -zavP  --exclude-from='./PaymentGateway/exclude.txt' -e 'ssh -p 4580' PaymentGateway/ merolagani@103.198.9.221:/home/merolagani/PaymentGateway/"
abbr syncrd "rsync -zavP  --exclude-from='./Redirection/exclude.txt' -e 'ssh -p 4580' Redirection/ merolagani@103.198.9.221:/home/merolagani/urlshortener/"
abbr syncsms "rsync -zavP  --exclude-from='./SMSMerolagani/exclude.txt' -e 'ssh -p 4580' SMSMerolagani/ merolagani@103.198.9.221:/home/merolagani/SMSMerolagani/"
abbr sshmrln "ssh -p 4580 merolagani@103.198.9.221"
abbr b "bat"
abbr c "clear"
abbr e "$EDITOR"
abbr l "ls"
abbr v "nvim"
abbr co "code ."
abbr py "python3"
abbr ka "killall"
abbr rd "rm -rf"
abbr ipy "ipython"
abbr mkd "mkdir -pv"
abbr jpn "jupyter-notebook"
abbr grep "grep --color=auto"
abbr diff "diff --color=auto"
abbr https "http --default-scheme=https"
abbr sd "sudo"
abbr SS "sudo systemctl"
abbr sv "sudo nvim"
abbr sdn "sudo shutdown now"
abbr npm "sudo npm"
abbr pip "sudo pip3"
abbr tlp "sudo tlp"
abbr yd "yarn dev"
abbr gi "go install"
abbr gr "go run ."
abbr gb "go build."
abbr godelete "rm $GOPATH/bin/"
abbr :q "exit"
abbr g "git"
abbr ga "git add"
abbr gp "git pull"
abbr gc "git commit"
abbr gd "git diff"
abbr gl "git log"
abbr gs "git status"
abbr gps "git push"
abbr lg "lazygit"
abbr da "docker attach"
abbr db "docker build"
abbr ds "docker start"
abbr di "docker images"
abbr dr "docker run"
abbr dk "docker kill"
abbr dca "docker container ps --filter 'status=running'"
abbr dcd "docker-compose down"
abbr dci "docker container ps --filter 'status=exited'"
abbr dcp "docker container prune"
abbr dcr "docker container rm"
abbr dcp "docker container prune"
abbr dcu "docker-compose up"
abbr dir "docker image rm"
abbr dst "docker stop"
abbr dvp "docker volume prune"
abbr dvr "docker volume rm"
abbr drr "docker run --rm"
abbr psh "pipenv shell"
abbr pi "pipenv install"
abbr tbe "tb -e @"
abbr tba "tb -t"
abbr tbg "tb -t @"
abbr tbd "tb -d"
abbr tbn "tb -n"
abbr tbc "tb -c"
abbr tbh "tb -h"
abbr tbp "tb -p @"
abbr tbng "tb -n @"
abbr tbcc "tb --clear"
abbr se "du -a ~/Documents/worker/dotfiles/scripts/* ~/.config/* | awk '{print \$2}' | fzf | xargs nvim" Scripts Folder Search tool
abbr vf "xdg-open (fzf) 2>/dev/null" 
abbr mrln "echo 'Mer0!@g@n!' | pbcopy"
