abbr c "clear"
abbr e "$EDITOR"
abbr h "echo 'Hello world'"
abbr f "fortune | lolcat"
abbr l "ls"
abbr r "ranger"
abbr v "nvim"
abbr x "sxiv -ft *"
abbr co "code ."
abbr py "python"
abbr ka "killall"
abbr rd "rm -rf"
abbr wc "nmcli con up DexterWifi_wlink"
abbr YT "youtube-viewer"
abbr ipy "ipython"
abbr mkd "mkdir -pv"
abbr jpn "jupyter-notebook"
abbr grep "grep --color=auto"
abbr diff "diff --color=auto"
abbr https "http --default-scheme=https"
abbr sd "sudo"
abbr SS "sudo systemctl"
abbr sv "sudo nvim"
abbr sdn "sudo shutdown now"
abbr npm "sudo npm"
abbr sdn "sudo shutdown now"
abbr pip "sudo pip"
abbr tlp "sudo tlp"
abbr snap "sudo snap"
abbr p "sudo pacman"
abbr y "yay"
abbr pi "sudo pacman -Sy"
abbr pr "sudo pacman -Rns"
abbr yi "yay -Sy"
abbr yr "yay -Rns"
abbr lsp "pacman -Qett --color=always | bat"
abbr lspy "pacman -Qm --color=always | bat"
abbr orp "sudo pacman -Rsun (pacman -Qqtd)"
abbr g "git"
abbr ga "git add"
abbr gp "git pull"
abbr gc "git commit"
abbr gl "git log"
abbr gs "git status"
abbr gps "git push"
abbr da "docker attach"
abbr db "docker build"
abbr ds "docker start"
abbr di "docker images"
abbr dr "docker run"
abbr dk "docker kill"
abbr dca "docker container ps --filter 'status=running'"
abbr dcd "docker-compose down"
abbr dci "docker container ps --filter 'status=exited'"
abbr dcp "docker container prune"
abbr dcr "docker container rm"
abbr dcp "docker container prune"
abbr dcu "docker-compose up"
abbr dir "docker image rm"
abbr dst "docker stop"
abbr dvp "docker volume prune"
abbr dvr "docker volume rm"
abbr pipsh "pipenv shell"
abbr pipi "pipenv install"
abbr tbe "tb -e @"
abbr tba "tb -t"
abbr tbg "tb -t @"
abbr tbd "tb -d"
abbr tbn "tb -n"
abbr tbc "tb -c"
abbr tbh "tb -h"
abbr tbp "tb -p @"
abbr tbng "tb -n @"
abbr tbcc "tb --clear"
abbr se "du -a ~/Documents/Maintenance/dotfiles/scripts/* ~/.config/* | awk '{print \$2}' | fzf | xargs -r $EDITOR"
abbr vf "xdg-open (fzf) 2>/dev/null"
abbr yt "youtube-dl --add-metadata -i"
abbr yta "youtube-dl --add-metadata -i -x -f bestaudio/best"
