# vim: filetype=sh
abbr h "cd ~/; and ls -a"
abbr d "cd ~/Documents; and ls -a"
abbr D "cd ~/Downloads; and ls -a"
abbr m "cd ~/Music; and ls -a"
abbr md "cd /media; and ls -a"
abbr pp "cd ~/Pictures; and ls -a"
abbr cf "cd ~/.config; and ls -a"
abbr sc "cd ~/.scripts; and ls -a"
abbr cff "cd ~/.config/fish; and ls -a"
abbr b "cd /mnt/disk_2/Programming_Contents/Books; and ls -a"
abbr vv "cd /mnt/disk_2/Videos; and ls -a"
abbr ef "cd /mnt/disk_2/Videos/Entertainment; and ls -a"
abbr wp "cd /mnt/disk_1/Media/Pictures/Wallpapers; and ls -a"
abbr po "cd /mnt/disk_2/Programming_Contents/Programming/Ongoing; and ls -a"
abbr mp "cd /mnt/disk_2/Programming_Contents/Programming/Ongoing/Spectra; and ls -a"
abbr Df "cd /mnt/disk_1; and ls -a"
abbr no "cd /mnt/disk_2/Programming_Contents/Programming/Notes; and ls -a"
abbr std "cd /mnt/disk_1/Study; and ls -a"
abbr rec "cd /mnt/disk_1/Recordings; and ls -a"
abbr stdn "cd /mnt/disk_1/Study/7th; and ls -a"
abbr bf "$EDITOR ~/.config/bmfiles"
abbr bd "$EDITOR ~/.config/bmdirs"
abbr cfb "$EDITOR ~/.bashrc"
abbr cfi "$EDITOR ~/.config/i3/config"
abbr cfp "$EDITOR ~/.profile"
abbr cfr "$EDITOR ~/.config/ranger/rc.conf"
abbr cfv "$EDITOR ~/.vimrc"
abbr cfz "$EDITOR ~/.zshrc"
abbr cfP "$EDITOR ~/.config/polybar/config"
abbr cfd "$EDITOR ~/.Xdefaults"
abbr cfu "$EDITOR ~/.config/newsboat/urls"
abbr cfn "$EDITOR ~/.config/newsboat/config"
abbr cfA "$EDITOR ~/.asoundrc"
abbr cfM "$EDITOR ~/.config/mpd/mpd.conf"
abbr fsa "$EDITOR ~/.config/.fshalias"
abbr cfzz "$EDITOR ~/.config/zathura/zathurarc"
abbr cfsx "$EDITOR ~/.config/sxiv/exec/key-handler"
abbr cfib "$EDITOR ~/.config/i3blocks/config"
abbr cfx "$EDITOR ~/.Xresources"
abbr cfmb "$EDITOR ~/.config/ncmpcpp/bindings"
abbr cfmc "$EDITOR ~/.config/ncmpcpp/config"
abbr cfml "$EDITOR ~/.config/mimeapps.list"
abbr cfdu "$EDITOR ~/.config/dunst/dunstrc"
abbr cfmpd "$EDITOR ~/.config/mpd/mpd.conf"
