# vim: filetype=sh
abbr h "cd ~/; and ls -a"
abbr d "cd ~/Documents; and ls -a"
abbr D "cd ~/Downloads; and ls -a"
abbr m "cd ~/Music; and ls -a"
abbr cf "cd ~/.config; and ls -a"
abbr sc "cd ~/.scripts; and ls -a"
abbr cff "cd ~/.config/fish; and ls -a"
abbr wrd "cd $WORK/Redirection; and ls -a"
abbr wpg "cd $WORK/PaymentGateway; and ls -a"
abbr po "cd ~/Documents/programming; and ls -a"
abbr en "cd ~/Documents/programming/Enterprise; and ls -a"
abbr xen "cd /Volumes/xen; and ls -a"
abbr bf "nvim ~/.config/bmfiles"
abbr bd "nvim ~/.config/bmdirs"
abbr cfb "nvim ~/.bashrc"
abbr cfp "nvim ~/.profile"
abbr cfv "nvim ~/.config/nvim/init.vim"
abbr cfz "nvim ~/.zshrc"
abbr cfs "nvim ~/.config/fish/settings.fish"
abbr fsa "nvim ~/.config/.fshalias"
