#!/bin/sh

IMAGE="/tmp/locked.png"
rm /tmp/locked.png
[ -f /usr/bin/scrot ] && scrot $IMAGE

xwobf -s 8 $IMAGE
# Pause music (mocp, mpd and send the pause key to all mpv videos):
mocp -P >/dev/null 2>&1
mpc pause >/dev/null 2>&1
pauseallmpv >/dev/null 2>&1

i3lock -e -f -c 000000 -i $IMAGE

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
