#!/bin/sh

screenshot_dir="$HOME/Pictures/Screenshots"
current_timestamp="$(date +%y%m%d-%H%M-%S).png"
pic_path_name="$screenshot_dir/pic-selected-$current_timestamp"

case "$(printf "a selected area\\ncurrent window\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfullscreen (copy)" | rofi -dmenu -l 6 -i -p "Screenshot which area?")" in
	"a selected area") maim -s $pic_path_name;;
	"current window") maim -i "$(xdotool getactivewindow)" $pic_path_name;;
	"full screen") maim $pic_path_name;;
	"a selected area (copy)") maim -s | xclip -selection clipboard -t image/png ;;
	"current window (copy)") maim -i | xclip -selection clipboard -t image/png ;;
	"full screen (copy)") maim | xclip -selection clipboard -t image/png ;;
esac

notify-send "Screenshot Captured" -i $pic_path_name
